import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers.dart';

class AddProductScreen extends ConsumerStatefulWidget { const AddProductScreen({super.key}); @override ConsumerState<AddProductScreen> createState()=>_AddProductScreenState(); }
class _AddProductScreenState extends ConsumerState<AddProductScreen>{
 final name=TextEditingController(), qty=TextEditingController(), price=TextEditingController(), location=TextEditingController();
 String grade='A', type='Conventional'; bool saving=false;
 @override void dispose(){name.dispose();qty.dispose();price.dispose();location.dispose();super.dispose();}
 Future<void> save() async { if(name.text.trim().isEmpty||location.text.trim().isEmpty||(double.tryParse(qty.text) ?? 0) <= 0 || (double.tryParse(price.text) ?? 0) <= 0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enter valid crop, quantity, price and location')));return;} setState(()=>saving=true); try{await ref.read(productRepositoryProvider).create({'crop_name':name.text.trim(),'quantity_kg':double.parse(qty.text),'price_per_kg':double.parse(price.text),'quality_grade':grade,'farming_type':type,'location':location.text.trim()}); ref.invalidate(myProductsProvider); if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Crop added successfully'))); Navigator.pop(context);}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>saving=false);}}
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Add Crop')),body:ListView(padding:const EdgeInsets.all(20),children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Crop name',prefixIcon:Icon(Icons.grass))),const SizedBox(height:14),TextField(controller:qty,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Quantity (kg)')),const SizedBox(height:14),TextField(controller:price,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Price per kg (₹)')),const SizedBox(height:14),DropdownButtonFormField(value:grade,items:['A','B','C'].map((x)=>DropdownMenuItem(value:x,child:Text('Grade $x'))).toList(),onChanged:(x)=>setState(()=>grade=x!),decoration:const InputDecoration(labelText:'Quality grade')),const SizedBox(height:14),DropdownButtonFormField(value:type,items:['Organic','Conventional'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>setState(()=>type=x!),decoration:const InputDecoration(labelText:'Farming type')),const SizedBox(height:14),TextField(controller:location,decoration:const InputDecoration(labelText:'Farm/location',prefixIcon:Icon(Icons.location_on))),const SizedBox(height:24),FilledButton(onPressed:saving?null:save,child:saving?const CircularProgressIndicator():const Text('Save Crop'))]));
}
